[package]
name = "flake-vm"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
description = "Stack-based bytecode virtual machine for Flake."

[dependencies]
flake-ast.workspace = true

[lints]
workspace = true
